
name: base_http
description: Dart package which has a basic http client with interceptior and environment configs.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.4
